source 'https://rubygems.org'


gem 'rails', '4.1.6'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
# gem 'bcrypt', '~> 3.1.7'
gem 'foundation-rails'
gem 'devise'
gem 'simple_form'
gem 'state_machine'
gem 'draper'
gem 'js-routes'
gem 'paperclip'
gem 'breadcrumbs_on_rails'
gem 'acts_as_commentable'

group :development do
  gem 'thin'
end

group :test do
  gem 'shoulda'
  gem 'factory_girl_rails'
end

group :development, :test do
  gem 'sqlite3'
  gem 'log_buddy'
end

group :assets do
  gem 'sass-rails', '~> 4.0.3'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
end
